#ifndef DMSYSTEM_GRAPH_H
#define DMSYSTEM_GRAPH_H

#include "dmsystem_unit_types.h"
#include "dmsystem_unit_defs.h"  // Generated by CMake from DMOD's api.h.in template

/**
 * @file dmsystem_graph.h
 * @brief Dependency-tree ordering for units (a stable topological sort).
 *
 * dmsystem_unit_topo_sort is a real DMOD module API (dmod_dmsystem_unit_api, same
 * convention as dmini's/dmosi's), defined in dmsystem_graph.c. Includes
 * dmsystem_unit_types.h rather than dmsystem_unit.h - see that header's note on why
 * dmsystem_graph.c must not re-include dmsystem_unit.h.
 */

/**
 * @brief Computes a start order for @p list that honors "after"/"requires" edges
 *
 * Uses Kahn's algorithm: at each pass, every not-yet-placed unit whose "after" and
 * "requires" dependencies are either already placed or reference no unit known to
 * @p list (an unresolvable dependency name is logged elsewhere and simply does not
 * block ordering) is appended to @p out_order, in the order units were declared.
 *
 * @param list       Units to order
 * @param out_order  Receives the indices of list->units in start order
 * @param max_order  Capacity of @p out_order (should be at least list->count)
 * @return Number of units placed. If less than list->count, the remaining units
 *         (not present in @p out_order) are involved in a dependency cycle.
 */
dmod_dmsystem_unit_api(1.0, size_t, _topo_sort, (dmsystem_unit_list_t* list, size_t out_order[], size_t max_order));

#endif /* DMSYSTEM_GRAPH_H */
