#ifndef DMSYSTEM_UNIT_H
#define DMSYSTEM_UNIT_H

#include "dmsystem_unit_types.h"
#include "dmsystem_unit_defs.h"  // Generated by CMake from DMOD's api.h.in template

/**
 * @file dmsystem_unit.h
 * @brief Unit-model DMOD module API: create/find units, parse argv/dependency lists.
 *
 * Lives in its own dmsystem_unit library module, separate from dmsystem_core, because
 * it has no dependency on dmini/dmosi - it only deals with plain strings and fixed-size
 * buffers. Every function here is a real DMOD module API (dmod_dmsystem_unit_api, same
 * convention as dmini's/dmosi's - the module name is the function prefix), defined in
 * dmsystem_unit.c, called across module boundaries by dmsystem_core (which requires
 * dmsystem_unit at runtime) and by test_dmsystem, which links only against
 * dmsystem_unit_if and calls these dynamically, exactly like it would call any other
 * DMOD module's API. Splitting it out this way means test_dmsystem never needs a live
 * dmini/dmosi backend to be connected just to load dmsystem_unit.dmf.
 *
 * @note Only dmsystem_unit.c may include this header (with DMOD_ENABLE_REGISTRATION
 *       defined as the very first line of the file, before any #include - that is
 *       what actually implements/exports these functions; dmod_defs.h's own include
 *       guard locks in whatever DMOD_ENABLE_REGISTRATION state was active the moment
 *       it is first processed in a translation unit, so defining it any later has no
 *       effect). dmsystem_graph.c needs the same types but must not re-include this
 *       header - see dmsystem_unit_types.h.
 */

/**
 * @brief Resets a unit list to empty
 */
dmod_dmsystem_unit_api(1.0, void, _list_init, (dmsystem_unit_list_t* list));

/**
 * @brief Appends a new, default-initialized unit named @p name
 *
 * @return Pointer to the new unit, or NULL if the list is full or the name is invalid
 */
dmod_dmsystem_unit_api(1.0, dmsystem_unit_t*, _list_add, (dmsystem_unit_list_t* list, const char* name));

/**
 * @brief Finds a unit by name
 *
 * @return Pointer to the unit, or NULL if not found
 */
dmod_dmsystem_unit_api(1.0, dmsystem_unit_t*, _list_find, (dmsystem_unit_list_t* list, const char* name));

/**
 * @brief Splits a semicolon/comma/whitespace-separated dependency list into trimmed names
 *
 * @param text          Raw dependency list (may be NULL or empty)
 * @param out           Output array of name buffers
 * @param max_entries   Capacity of @p out
 * @return Number of names written to @p out
 */
dmod_dmsystem_unit_api(1.0, size_t, _parse_dependency_list,
    (const char* text, char out[][DMOD_MAX_MODULE_NAME_LENGTH], size_t max_entries));

/**
 * @brief Sets a unit's exec/argv from the module name and a raw whitespace-separated args string
 *
 * argv[0] is set to the unit's own exec buffer; further tokens are split out of a private
 * copy of @p args held in the unit (args_storage), so both remain valid for the unit's lifetime.
 *
 * @return The resulting argc
 */
dmod_dmsystem_unit_api(1.0, int, _build_argv, (dmsystem_unit_t* unit, const char* exec, const char* args));

/**
 * @brief Parses a "type=" value ("oneshot" or anything else, which defaults to "simple")
 */
dmod_dmsystem_unit_api(1.0, dmsystem_unit_type_t, _parse_type, (const char* text));

/**
 * @brief Parses a "restart=" value ("always" or anything else, which defaults to "no")
 */
dmod_dmsystem_unit_api(1.0, dmsystem_restart_policy_t, _parse_restart, (const char* text));

#endif /* DMSYSTEM_UNIT_H */
