#ifndef DMSYSTEM_CORE_H
#define DMSYSTEM_CORE_H

#include "dmsystem_core_defs.h"  // Generated by CMake from DMOD's api.h.in template

/**
 * @file dmsystem_core.h
 * @brief Top-level orchestration: load config, order units, start them, supervise.
 *
 * dmsystem_core_run is the one DMOD module API this module exposes to the dmsystem
 * executable (dmod_dmsystem_core_api, same convention as dmini's/dmosi's - the module
 * name is the function prefix) - everything else (INI loading, process spawning) is
 * orchestrated internally from dmsystem_core.c.
 *
 * @note DMOD_ENABLE_REGISTRATION must be defined as the very first line of
 *       dmsystem_core.c, before any #include - see dmsystem_unit.h's note on why.
 */

/**
 * @brief Scans @p units_dir for unit files, starts every unit in dependency order,
 *        and then supervises the "simple" (long-running) units until none are left
 *        running.
 *
 * Every "*.ini" file directly inside @p units_dir is one unit, named after its
 * filename with the extension stripped (see dmsystem_config.h) - there is no single
 * master config file, so adding a service is just dropping its own unit file into
 * the directory.
 *
 * Units are started in an order that respects "after"/"requires": a unit is only
 * started once every unit it lists is already running (for "simple" dependencies)
 * or has completed (for "oneshot" dependencies). A unit that "requires" another
 * unit which failed to start (or was itself skipped) is skipped in turn; a unit
 * that merely comes "after" a failed one still starts. Units caught in a
 * dependency cycle are skipped and logged as such.
 *
 * @param units_dir Path to the directory containing unit files
 * @return 0 if every unit that was actually started/run succeeded and there is
 *         nothing left to supervise, a positive count of failed units otherwise,
 *         or a negative errno-style code if @p units_dir could not even be opened
 */
dmod_dmsystem_core_api(1.0, int, _run, (const char* units_dir));

#endif /* DMSYSTEM_CORE_H */
