#ifndef DMSYSTEM_CORE_H
#define DMSYSTEM_CORE_H

#include "dmsystem_unit_types.h"
#include "dmsystem_core_defs.h"  // Generated by CMake from DMOD's api.h.in template

/**
 * @file dmsystem_core.h
 * @brief Top-level orchestration: load config, order units, start them, supervise -
 *        plus the query/control API used by the `service` CLI (service/service.c) to
 *        inspect and manage units in an already-running dmsystem.
 *
 * Every function here is a real DMOD module API (dmod_dmsystem_core_api, same
 * convention as dmini's/dmosi's - the module name is the function prefix). dmsystem
 * itself only ever calls dmsystem_core_run; the get/find/start/stop/restart functions
 * are for `service`, a separate Application module that requires dmsystem_core exactly
 * like dmsystem does. Because DMOD loads a given Library module at most once and
 * shares that one instance across every Application that requires it (reference
 * counted, like a conventional shared library), `service` observes and controls the
 * very same in-memory unit list dmsystem_core_run is supervising - there is no separate
 * IPC channel. All of it is guarded by an internal mutex (see dmsystem_core.c) since
 * dmsystem's own supervise loop and `service`'s calls run on different threads/processes.
 *
 * @note DMOD_ENABLE_REGISTRATION must be defined as the very first line of
 *       dmsystem_core.c, before any #include - see dmsystem_unit.h's note on why.
 */

/**
 * @brief Scans @p units_dir for unit files, starts every unit in dependency order,
 *        and then supervises the "simple" (long-running) units until none are left
 *        running.
 *
 * Every "*.ini" file directly inside @p units_dir is one unit, named after its
 * filename with the extension stripped (see dmsystem_config.h) - there is no single
 * master config file, so adding a service is just dropping its own unit file into
 * the directory.
 *
 * Units are started in an order that respects "after"/"requires": a unit is only
 * started once every unit it lists is already running (for "simple" dependencies)
 * or has completed (for "oneshot" dependencies). A unit that "requires" another
 * unit which failed to start (or was itself skipped) is skipped in turn; a unit
 * that merely comes "after" a failed one still starts. Units caught in a
 * dependency cycle are skipped and logged as such.
 *
 * @param units_dir Path to the directory containing unit files
 * @return 0 if every unit that was actually started/run succeeded and there is
 *         nothing left to supervise, a positive count of failed units otherwise,
 *         or a negative errno-style code if @p units_dir could not even be opened
 */
dmod_dmsystem_core_api(1.0, int, _run, (const char* units_dir));

/**
 * @brief Number of units currently known to a running dmsystem
 *
 * @return The unit count, or 0 if dmsystem_core_run has not (yet) been started -
 *         indistinguishable from a units directory that legitimately had zero unit
 *         files in it.
 */
dmod_dmsystem_core_api(1.0, size_t, _get_unit_count, (void));

/**
 * @brief Gets a status snapshot for the unit at position @p index
 *
 * Index order matches the order units were declared in dmsystem_core_run's units
 * directory scan; use dmsystem_core_get_unit_count() to find the valid range. Mainly
 * useful for listing every unit (e.g. `service status` with no unit name).
 *
 * @param index Zero-based unit index
 * @param out   Receives the status snapshot; untouched if this returns false
 * @return true if @p index was in range, false otherwise (or if dmsystem is not running)
 */
dmod_dmsystem_core_api(1.0, bool, _get_unit_status, (size_t index, dmsystem_unit_status_t* out));

/**
 * @brief Gets a status snapshot for the unit named @p name
 *
 * @param name Unit name (its unit file's name, without the ".ini" extension)
 * @param out  Receives the status snapshot; untouched if this returns false
 * @return true if a unit named @p name was found, false otherwise
 */
dmod_dmsystem_core_api(1.0, bool, _find_unit_status, (const char* name, dmsystem_unit_status_t* out));

/**
 * @brief Starts the named unit if it is not already running
 *
 * Unlike the startup order dmsystem_core_run computes from "after"/"requires", this
 * acts on exactly the named unit and does not cascade to its dependencies - the same
 * scope as `systemctl start <unit>` without `--now`-style dependency chasing.
 *
 * @param name Unit name
 * @return true if the unit was found and (already running, or successfully started);
 *         false if not found or the start attempt itself failed
 */
dmod_dmsystem_core_api(1.0, bool, _start_unit, (const char* name));

/**
 * @brief Stops the named unit if it is currently running
 *
 * Kills the unit's process and marks it DMSYSTEM_UNIT_STATE_STOPPED; the supervise
 * loop's restart=always handling only applies to units that terminate on their own,
 * so a unit stopped this way is not restarted automatically.
 *
 * @param name Unit name
 * @return true if the unit was found and running (and is now stopped); false if not
 *         found or not running
 */
dmod_dmsystem_core_api(1.0, bool, _stop_unit, (const char* name));

/**
 * @brief Stops the named unit if running, then starts it
 *
 * @param name Unit name
 * @return true if the unit was found and the restart succeeded; false if not found
 *         or the start attempt failed
 */
dmod_dmsystem_core_api(1.0, bool, _restart_unit, (const char* name));

#endif /* DMSYSTEM_CORE_H */
